@startuml
hide circle
skinparam nodesep 70
class Case
class Container
class Block
abstract class Analysis
abstract class Stain
class Slide
class Report
Case *-->  Container
Case *-->  Block
Case *-->  Analysis
Block  -l->  Container 
Block *-->  Slide
Case *->  Report
Slide -> Stain
@enduml
